---

#To install pip and the AWS CLI

- stat: path=/home/ec2-user/epel-release-latest-7.noarch.rpm
  register: st
- name: epel realse 
  get_url: 
    url: http://fedora-epel.mirrors.tds.net/fedora-epel//epel-release-latest-7.noarch.rpm
    dest: /home/ec2-user/
  action:
    when: not st.stat.exists
 
- name: install rpm
  yum:
     name: epel-release-latest-7.noarch.rpm
     state: present
   
- name : python pip
  yum : 
   name :  python-pip
   state : present 
   update_cache: yes

- name : Install awscli
  pip :
   name : awscli
